#!/usr/bin/env python

#
# Wrapper for controlling various music players, so that you can define keyboard
# shortcuts that work for whatever player you are using.  Ideally it will still
# work even if multiple players are running if all but one are 'stopped', but
# some music players do not have such a state or it cannot be determined.
#

import playerdo.main
import sys

# Execute commands:

def main(command, players):
    if command == "test":
        playerdo.main.do_test(players)
    elif command == "help":
        playerdo.main.print_help(players)
    else:
        playerdo.main.do_command(command, players)


if __name__ == '__main__':
    import sys
    main(sys.argv[1], playerdo.main.find_players())

